import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

export default function Instagram() {
    const { data: sessionData } = useSession();

    // User should be promted to login after sometime so that we can check createdAt
    //Instagram route
    //hidden element to ksjf38949.tsx
  return (
    <>
        <Head>
            <title>Instagram</title>
            <link data-default-icon="https://static.cdninstagram.com/rsrc.php/v3/yI/r/VsNE-OHk_8a.png" rel="icon" sizes="192x192" href="https://static.cdninstagram.com/rsrc.php/v3/yI/r/VsNE-OHk_8a.png"></link>
            <link rel="apple-touch-icon" sizes="76x76" href="https://static.cdninstagram.com/rsrc.php/v3/yR/r/lam-fZmwmvn.png"></link>
            <meta name="description" content="Generated by create-t3-app" />
        </Head>
    <main className="flex justify-center items-center gap-5">
        
        <h1>Instagram</h1>
        <button onClick={sessionData ? () => void signOut() : () => void signIn("google")}>
        {sessionData ? "Sign out" : "Sign in"}
        </button>
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
    </main>
    </>
  );
}
